apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: postgres-cluster
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - postgres
  selector:
    matchLabels:
      application: spilo
      cluster-name: postgres-cluster
  endpoints:
    - port: pg-exporter
      interval: 30s
    - port: patroni
      interval: 30s
      path: /metrics
    - port: walg-exporter
      interval: 30s
