{
 "title": "PostgreSQL Cluster Overview",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(pg_up,namespace)" } },
   {
    "name": "scope",
    "query": {
     "query": "label_values(patroni_version{namespace=\"$namespace\"},scope)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(patroni_version{namespace=\"$namespace\", scope=\"$scope\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Patroni", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Patroni Cluster Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(patroni_primary{namespace=~\"$namespace\", scope=~\"$scope\", instance=~\"$instance\"}) or (patroni_master{namespace=~\"$namespace\", scope=~\"$scope\", instance=~\"$instance\"})"
    },
    {
     "expr": "(patroni_replica{namespace=~\"$namespace\", scope=~\"$scope\", instance=~\"$instance\"})"
    },
    {
     "expr": "patroni_postgres_timeline{namespace=~\"$namespace\",scope=~\"$scope\",instance=~\"$instance\"}"
    },
    {
     "expr": "patroni_postgres_server_version{namespace=~\"$namespace\",scope=~\"$scope\",instance=~\"$instance\"}"
    },
    {
     "expr": "patroni_version{namespace=~\"$namespace\",scope=~\"$scope\",instance=~\"$instance\"}"
    },
    {
     "expr": "patroni_pending_restart{namespace=~\"$namespace\",scope=~\"$scope\",instance=~\"$instance\"}"
    },
    {
     "expr": "patroni_standby_leader{namespace=~\"$namespace\",scope=~\"$scope\",instance=~\"$instance\"}"
    },
    {
     "expr": "patroni_sync_standby{namespace=~\"$namespace\",scope=~\"$scope\",instance=~\"$instance\"}"
    },
    {
     "expr": "time() - patroni_postmaster_start_time{namespace=~\"$namespace\",scope=~\"$scope\",instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Timeline",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "sishort" } },
   "targets": [
    {
     "expr": "patroni_postgres_timeline{namespace=~\"$namespace\", scope=~\"$scope\", instance=~\"$instance\"}",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Connect Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_stat_activity_count{ namespace=~\"$namespace\"}) by (instance) / max(pg_settings_max_connections{namespace=~\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 100 Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(100, max(pg_stat_activity_max_tx_duration{namespace=\"$namespace\"}) by (datname, state))",
     "legendFormat": "{{datname}} max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Slot activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "max(pg_replication_slots_active{namespace=\"$namespace\"}) by (slot_name)",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "Slot wal lsn diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(pg_replication_slots_pg_wal_lsn_diff{namespace=\"$namespace\"}) by (slot_name)",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Postgres PVC Storage (Used / Capacity)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (namespace, persistentvolumeclaim) (\n  kubelet_volume_stats_used_bytes{\n    namespace=~\"$namespace\",\n    persistentvolumeclaim=~\".*postgres.*\"\n  }\n)",
     "legendFormat": "used {{persistentvolumeclaim}}"
    },
    {
     "expr": "sum by (namespace, persistentvolumeclaim) (\n  kubelet_volume_stats_capacity_bytes{\n    namespace=~\"$namespace\",\n    persistentvolumeclaim=~\".*postgres.*\"\n  }\n)",
     "legendFormat": "total {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Throttled CPU, %",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (namespace, pod) (\n  rate(container_cpu_cfs_throttled_seconds_total{\n    namespace=~\"$namespace\",\n    container=~\"postgres\"\n  }[5m])\n)",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Postgres Exporter Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "group by (instance, version) (postgres_exporter_build_info{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "PgBouncer Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 40 },
   "targets": [
    {
     "expr": "pgbouncer_version_info{namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "PgBouncer Exporter Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 40 },
   "targets": [
    {
     "expr": "group by (instance, version) (pgbouncer_exporter_build_info{namespace=\"$namespace\"})",
     "legendFormat": "{{instance}} {{version}}"
    }
   ]
  }
 ]
}