{
 "title": "PostgreSQL Cluster Replication PG Exporter",
 "tags": [ "pg_exporter" ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   { "name": "namespace", "label": "namespace", "query": { "query": "label_values(pg_up,namespace)" } },
   {
    "name": "primary",
    "label": "primary",
    "query": {
     "query": "query_result(sum without(instance) (label_replace(patroni_primary{namespace=~\"$namespace\"} == 1, \"ip\", \"$1\", \"instance\", \"([^:]+):.*\")) * on(ip) group_left(instance) label_replace(pg_up{namespace=~\"$namespace\"}, \"ip\", \"$1\", \"instance\", \"([^:]+):.*\"))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Leader",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool" } },
   "targets": [
    {
     "expr": "(patroni_primary{namespace=~\"$namespace\"}) == 1 or (patroni_master{namespace=~\"$namespace\"}) ==1",
     "legendFormat": "Leader : {{instance}}"
    }
   ]
  },
  {
   "title": "Replication Slots",
   "type": "table",
   "description": "Replication Slot of cluster $cluster on Primary Instance $primary",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "max by (slot_name) (pg_slot_active{namespace=\"$namespace\", instance=\"$primary\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (ins, slot_name, datname) (pg_slot_retained_bytes{namespace=\"$namespace\", instance=\"$primary\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (slot_name) (pg_slot_temporary{namespace=\"$namespace\", instance=\"$primary\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (slot_name) (pg_slot_wal_status{namespace=\"$namespace\", instance=\"$primary\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (slot_name) (pg_slot_restart_lsn{namespace=\"$namespace\", instance=\"$primary\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TimeLine",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pg_timeline_id{namespace=\"$namespace\", instance=\"$primary\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Replication Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_repl_replay_diff{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}} - {{appname}}:{{address}}"
    }
   ]
  },
  { "title": "Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Replication Lag in Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_repl_replay_diff{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}} : {{usename}} : {{appname}} : {{address}}"
    }
   ]
  },
  {
   "title": "Replication Lag in Seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_repl_replay_lag{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}} : {{usename}} : {{appname}} : {{address}}"
    }
   ]
  },
  {
   "title": "Replication Lag in Detail",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_repl_lsn{namespace=\"$namespace\"} - pg_repl_sent_lsn{namespace=\"$namespace\"}",
     "legendFormat": "[SENT] {{instance}} : {{usename}} : {{appname}} : {{address}}"
    },
    {
     "expr": "pg_repl_sent_lsn{namespace=\"$namespace\"} - pg_repl_write_lsn{namespace=\"$namespace\"}",
     "legendFormat": "[WRITE] {{instance}} : {{usename}} : {{appname}} : {{address}}"
    },
    {
     "expr": "pg_repl_write_lsn{namespace=\"$namespace\"} - pg_repl_flush_lsn{namespace=\"$namespace\"}",
     "legendFormat": "[FLUSH] {{instance}} : {{usename}} : {{appname}} : {{address}}"
    },
    {
     "expr": "pg_repl_replay_lsn{namespace=\"$namespace\"} - pg_repl_flush_lsn{namespace=\"$namespace\"}",
     "legendFormat": "[REPLAY] {{instance}} : {{usename}} : {{appname}} : {{address}}"
    }
   ]
  },
  {
   "title": "Replication Lag in Seconds (Follower's View)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "pg_lag{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "LSN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Replication LSN Progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "max(pg_repl_lsn{namespace=\"$namespace\"})",
     "legendFormat": "Current repl LSN"
    },
    {
     "expr": "pg_repl_replay_lsn{namespace=\"$namespace\"}",
     "legendFormat": "replay : {{appname}}"
    },
    {
     "expr": "pg_repl_flush_lsn{namespace=\"$namespace\"}",
     "legendFormat": "flush : {{appname}}"
    },
    {
     "expr": "pg_repl_write_lsn{namespace=\"$namespace\"}",
     "legendFormat": "write : {{appname}}"
    },
    {
     "expr": "pg_slot_restart_lsn{namespace=\"$namespace\"}",
     "legendFormat": "slot restart : {{slot_name}} : {{instance}}"
    }
   ]
  },
  {
   "title": "Checkpoint LSN Progress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "max(pg_lsn{namespace=\"$namespace\"})",
     "legendFormat": "Current LSN"
    },
    {
     "expr": "pg_checkpoint_checkpoint_lsn{namespace=\"$namespace\", instance=\"$primary\"}",
     "legendFormat": "Checkpoint Leader $primary"
    },
    {
     "expr": "pg_checkpoint_checkpoint_lsn{namespace=\"$namespace\", instance!=\"$primary\"}",
     "legendFormat": "Checkpoint Follower {{ instance }}"
    },
    {
     "expr": "pg_checkpoint_redo_lsn{namespace=\"$namespace\", instance!=\"$primary\"}",
     "legendFormat": "Redo {{ instance}}"
    }
   ]
  },
  {
   "title": "XID",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true
  },
  {
   "title": "XMax Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "pg_xact_xmax{namespace=\"$namespace\"}",
     "legendFormat": "xmax : {{instance}}"
    }
   ]
  },
  {
   "title": "XMin Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
   "targets": [
    {
     "expr": "pg_xact_xmin{namespace=\"$namespace\"}",
     "legendFormat": "xmin : {{instance}}"
    }
   ]
  },
  {
   "title": "XMin Horizon",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "max(pg_xact_xmax{namespace=\"$namespace\"})",
     "legendFormat": "XMax"
    },
    {
     "expr": "pg_repl_backend_xmin{namespace=\"$namespace\"}",
     "legendFormat": "repl: {{ appname }}"
    },
    {
     "expr": "pg_slot_catalog_xmin{namespace=\"$namespace\"}",
     "legendFormat": "slot : {{ instance }} : {{ slot_name }}"
    }
   ]
  },
  {
   "title": "Xact in Progress",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "pg_xact_xnum{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Slot", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "Slot Retained Bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_slot_retained_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}} : {{slot_name}}"
    }
   ]
  },
  { "title": "Logical", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "title": "Publications",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 79 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance)(pg_pubrel_count{instance=\"$primary\"}) > bool 0 or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Publication Table Count",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 3, "y": 79 },
   "targets": [
    {
     "expr": "pg_pubrel_count{instance=\"$primary\"}",
     "legendFormat": "{{ pubname }}"
    }
   ]
  },
  {
   "title": "Subscription Table Count by State",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 79 },
   "targets": [
    {
     "expr": "pg_subrel_count{instance=\"$primary\"}",
     "legendFormat": "{{ subname }} : {{ state }}"
    }
   ]
  },
  {
   "title": "Subscriptions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 84 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (instance)(pg_sub_id{instance=\"$primary\"}) or on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}