{
 "title": "PostgreSQL Cluster Overview PG Exporter",
 "tags": [ "pg_exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(patroni_version,namespace)"
    }
   },
   {
    "name": "scope",
    "query": {
     "query": "label_values(patroni_version{namespace=\"$namespace\"},scope)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(patroni_version{namespace=\"$namespace\", scope=\"$scope\"},instance)"
    }
   },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Patroni", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Patroni Cluster Status", "type": "library-panel-ref", "gridPos": { "h": 6, "w": 24, "x": 0, "y": 1 } },
  { "title": "Timeline", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 7 } },
  { "title": "PostgreSQL", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Database List",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "max(pg_size_bytes{namespace=~\"$namespace\", datname!~\"template[01]|postgres\"}) by (datname)"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(\n  sum(rate(pg_db_blk_read_time{namespace=~\"$namespace\"}[1m])) by (instance)\n  +\n  sum(rate(pg_db_blk_write_time{namespace=~\"$namespace\"}[1m])) by (instance)\n)\n/\nsum(rate(pg_db_blks_read{namespace=~\"$namespace\"}[1m]))\nby (instance)\n* 1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum(rate(pg_db_xact_commit{namespace=~\"$namespace\"}[1m])) by (instance)\n+ \nsum(rate(pg_db_xact_rollback{namespace=~\"$namespace\"}[1m])) by (instance)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Connect Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(pg_activity_count{namespace=~\"$namespace\"}) by (instance) / max(pg_setting_max_connections{namespace=~\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (\n  sum(\n    rate(pg_db_blks_hit{namespace=~\"$namespace\"}[1m])\n  ) by (instance)\n  /\n  (\n    sum(\n      rate(pg_db_blks_read{namespace=~\"$namespace\"}[1m])\n    ) by (instance)\n    +\n    sum(\n      rate(pg_db_blks_hit{namespace=~\"$namespace\"}[1m])\n    ) by (instance)\n  )\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Count Connect Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum(pg_activity_count{namespace=~\"$namespace\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Top 100 Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(100, max(pg_activity_max_tx_duration{namespace=\"$namespace\"}) by (datname, state))",
     "legendFormat": "{{datname}} max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Slot activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "pg_slot_active{namespace=\"$namespace\"}",
     "legendFormat": "{{slot_name}}"
    }
   ]
  },
  {
   "title": "Slot retained bytes",
   "type": "timeseries",
   "description": "объём WAL в байтах, удерживаемый слотом — то есть разница между текущим LSN и restart_lsn слота",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_slot_retained_bytes{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}} : {{datname}} : {{slot_name}} : {{slot_type}}"
    }
   ]
  },
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 } },
  {
   "title": "Postgres PVC Storage (Used / Capacity)",
   "type": "library-panel-ref",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 51 }
  },
  { "title": "Throttled CPU, %", "type": "library-panel-ref", "gridPos": { "h": 5, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "PG Exporter Version",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "group by (instance, version) (pg_exporter_build_info{namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "WAL-G", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  { "title": "Last basebackup date", "type": "library-panel-ref", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 70 } }
 ]
}