{
 "title": "PostgreSQL Performance Monitoring PG Exporter",
 "description": "PostgreSQL Performance Monitoring",
 "tags": [ "pg_exporter" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": { "query": "label_values(pg_up, namespace)" } },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(pg_up{namespace=\"$namespace\"}, instance)"
    }
   },
   {
    "name": "node_instance",
    "label": "Node",
    "query": {
     "query": "query_result(count(kube_pod_info{namespace=\"$namespace\"}) by (node) * on(node) group_left(instance) label_replace(count(node_uname_info) by (nodename, instance), \"node\", \"$1\", \"nodename\", \"(.*)\"))"
    }
   },
   {
    "name": "db",
    "query": {
     "query": "label_values(pg_size_bytes{namespace=\"$namespace\", instance=\"$instance\"},datname)"
    }
   },
   {
    "name": "disk",
    "label": "Disk",
    "query": {
     "query": "label_values(node_disk_read_bytes_total{instance=~\"$node_instance\"},device)"
    }
   },
   { "name": "interval", "label": "interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Instance settings", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_version{instance=\"$instance\"})",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Max Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_max_connections{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Shared Buffers",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_shared_buffers{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Effective Cache",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_effective_cache_size{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max Worker Processes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_max_worker_processes{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max Parallel Workers ",
   "type": "stat",
   "description": "Max Parallel Workers per gather",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_max_parallel_workers_per_gather{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Max WAL Size",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_max_wal_size{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Autovacuum naptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_cstm_autovacuum_naptime_seconds{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Seq Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_cstm_seq_page_cost{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Maintenance Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 14, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_maintenance_work_mem{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Work Mem",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_work_mem{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Random Page Cost",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(pg_setting_cstm_random_page_cost{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Replication",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(pg_repl_replay_diff{namespace=\"$namespace\"}) by (address)",
     "legendFormat": "wal_lsn_diff::bytes::{{ address}}"
    },
    {
     "expr": "max(irate(pg_repl_replay_lag{namespace=\"$namespace\"}[5m])) by (address)",
     "legendFormat": "repl_replay_lag::seconds::{{ address}}"
    }
   ]
  },
  {
   "title": "Connections Utilisation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(pg_activity_count{instance=\"$instance\"})\n",
     "legendFormat": "Current connections"
    },
    {
     "expr": "max(pg_setting_max_connections{instance=\"$instance\"})",
     "legendFormat": "Max connections"
    }
   ]
  },
  {
   "title": "Patroni inctance status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "label_replace((patroni_primary{namespace=~\"$namespace\"}) or (patroni_master{namespace=~\"$namespace\"}), \"ip\", \"$1\", \"instance\", \"([^:]+):.*\")\nand on(ip)\nlabel_replace(pg_up{namespace=~\"$namespace\", instance=~\"$instance\"}, \"ip\", \"$1\", \"instance\", \"([^:]+):.*\")"
    }
   ]
  },
  {
   "title": "WAL size",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_wal_bytes{namespace=\"$namespace\", instance=\"$instance\"}",
     "legendFormat": "WAL size"
    }
   ]
  },
  {
   "title": "Patroni",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Patroni Cluster Status",
     "type": "table",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "(patroni_primary{namespace=~\"$namespace\"}) or (patroni_master{namespace=~\"$namespace\"})\n"
      },
      {
       "expr": "patroni_pending_restart{namespace=~\"$namespace\"}"
      },
      {
       "expr": "patroni_standby_leader{namespace=~\"$namespace\"}"
      },
      {
       "expr": "patroni_sync_standby{namespace=~\"$namespace\"}"
      },
      {
       "expr": "patroni_postgres_server_version{namespace=~\"$namespace\"}",
       "legendFormat": "__auto"
      },
      {
       "expr": "patroni_version{namespace=~\"$namespace\"}"
      },
      {
       "expr": "patroni_replica{namespace=~\"$namespace\"}"
      }
     ]
    }
   ]
  },
  { "title": "Host stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total CPU utilization",
   "type": "timeseries",
   "description": "Total CPU utilization (all cores). 100% here means there is no CPU idle time at all. You can get per core usage at the _CPUs_ section and per application usage at the _Applications monitoring_ section.\n\nKeep an eye on **iowait**. If it is constantly high, your disks are a bottleneck and they slow your system down.\n\nAn important metric worth monitoring, is **softirq**. A constantly high percentage of softirq may indicate network driver issues.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=~\"$node_instance\"}[5m])))",
     "legendFormat": "{{dimension}}"
    }
   ]
  },
  {
   "title": "Free System RAM",
   "type": "timeseries",
   "description": "System Random Access Memory (i.e. physical memory) usage.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemAvailable_bytes{instance=~\"$node_instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "Total Disk I/O, for all physical disks. You can get detailed information about each disk at the _Disks_ section and per application Disk usage at the _Applications Monitoring_ section.\n\nPhysical are all the disks that are listed in `/sys/block`, but do not exist in `/sys/devices/virtual/block`.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "(\n  rate(node_disk_read_bytes_total{device=~\"$disk\", instance=~\"$node_instance\"}[5m])\n+ rate(node_disk_written_bytes_total{device=~\"$disk\", instance=~\"$node_instance\"}[5m])\n) / 1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{device=~\"$disk\", instance=~\"$node_instance\"}[5m]) / 1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Disk writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(node_disk_written_bytes_total{device=~\"$disk\", instance=~\"$node_instance\"}[5m]) / 1024",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Used memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((node_memory_MemTotal_bytes{instance=~\"$node_instance\"} - node_memory_MemFree_bytes{instance=~\"$node_instance\"}) / (node_memory_MemTotal_bytes{instance=~\"$node_instance\"} )) * 100",
     "legendFormat": "$instance"
    }
   ]
  },
  {
   "title": "CPU Busy Percent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(((count(count(node_cpu_seconds_total{instance=~\"$node_instance\"}) by (cpu))) - avg(sum by (mode)(irate(node_cpu_seconds_total{mode='idle',instance=~\"$node_instance\"}[5m])))) * 100) / count(count(node_cpu_seconds_total{instance=~\"$node_instance\"}) by (cpu))",
     "legendFormat": "CPU busy % - $instance"
    }
   ]
  },
  {
   "title": "Disk space under DBs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_filesystem_free_bytes{instance=~\"$node_instance\", device!~'tmpfs', mountpoint!~'/boot/.+'}",
     "legendFormat": "free space :: $instance {{ mountpoint }}"
    },
    {
     "expr": "node_filesystem_size_bytes{instance=~\"$node_instance\", device!~'tmpfs', mountpoint!~'/boot/.+'}",
     "legendFormat": "total space :: $instance {{ mountpoint }}"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$node_instance\"}[20s]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$node_instance\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{instance=~\"$node_instance\"}[20s]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$node_instance\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{device!~\"dm-.+\", device!~\"sr.+\", instance=~\"$node_instance\"}[1m]) / rate(node_disk_reads_completed_total{device!~\"dm-.+\", device!~\"sr.+\", instance=~\"$node_instance\"}[1m]) * 1000000",
     "legendFormat": "{{instance}} - {{device}} "
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "rate(node_disk_write_time_seconds_total{device!~\"dm-.+\", device!~\"sr.+\", instance=~\"$node_instance\"}[1m]) / rate(node_disk_writes_completed_total{device!~\"dm-.+\", device!~\"sr.+\", instance=~\"$node_instance\"}[1m]) * 1000000",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Read IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{device!~\"dm-.+\", device!~\"sr.+\", instance=~\"$node_instance\"}[1m]) ",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "Write IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(node_disk_writes_completed_total{device!~\"dm-.+\", device!~\"sr.+\", instance=~\"$node_instance\"}[1m]) ",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  { "title": "DB Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Top 100 Connections in detail",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "topk(100, max(pg_activity_count{instance=\"$instance\", datname=~\"($db)\"}) by (datname, state))",
     "legendFormat": "{{datname}} {{state}}"
    }
   ]
  },
  {
   "title": "Top 100 Transactions per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100, max(irate(pg_db_xact_commit{instance=\"$instance\", datname=~\"($db)\"}[5m])) by (datname))",
     "legendFormat": "{{datname}} commits"
    },
    {
     "expr": "topk(100, max(irate(pg_db_xact_rollback{instance=\"$instance\", datname=~\"($db)\"}[5m])) by (datname))",
     "legendFormat": "{{datname}} rollbacks"
    }
   ]
  },
  {
   "title": "Top 100 Read Stat per second",
   "type": "timeseries",
   "description": "- fetched rows - number of rows return to client\n- return rows - number of rows scan for execute queries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100, max(irate(pg_db_tup_fetched{instance=\"$instance\", datname=~\"($db)\"}[5m])) by (datname))",
     "legendFormat": "{{datname}} fetched rows"
    },
    {
     "expr": "topk(100, max(irate(pg_db_tup_returned{instance=\"$instance\", datname=~\"($db)\"}[5m])) by (datname))",
     "legendFormat": "{{datname}} return rows"
    }
   ]
  },
  {
   "title": "Top 100 effective scan avg 5m",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "targets": [
    {
     "expr": "topk(100, max(delta(pg_db_tup_fetched{instance=\"$instance\", datname=~\"($db)\"}[5m])) by (datname) / ((max(delta(pg_db_tup_returned{instance=\"$instance\", datname=~\"($db)\"}[5m])) by (datname))/100))",
     "legendFormat": "{{ datname }} effective scan"
    }
   ]
  },
  {
   "title": "Top 100 Longest Transaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "topk(100, max(pg_activity_max_tx_duration{instance=\"$instance\", datname=~\"($db)\"}) by (datname, state))",
     "legendFormat": "{{datname}} max_tx_duration [{{state}}]"
    }
   ]
  },
  {
   "title": "Top 100 Change Stats per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(100, max(irate(pg_db_tup_inserted{instance=\"$instance\", datname=~\"($db)\"}[5m])) by (datname))",
     "legendFormat": "{{datname}} INSERT"
    },
    {
     "expr": "topk(100, max(irate(pg_db_tup_updated{instance=\"$instance\", datname=~\"($db)\"}[5m])) by (datname))",
     "legendFormat": "{{datname}} UPDATE"
    },
    {
     "expr": "irate(pg_db_tup_deleted{instance=\"$instance\"}[5m])",
     "legendFormat": "{{datname}} DELETE"
    }
   ]
  },
  {
   "title": "Database size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 99 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(pg_size_bytes{instance=\"$instance\", datname=~\"($db)\"}) by (datname)",
     "legendFormat": "{{ datname }}"
    },
    {
     "expr": "sum(max(pg_size_bytes{instance=\"$instance\", datname=~\"($db)\"}) by (datname))",
     "legendFormat": "All DB's"
    }
   ]
  },
  {
   "title": "Bottom 100 Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 99 },
   "targets": [
    {
     "expr": "bottomk(100, max(pg_db_blks_hit{instance=\"$instance\", datname=~\"($db)\"} / (pg_db_blks_read{instance=\"$instance\", datname=~\"($db)\"} + pg_db_blks_hit{instance=\"$instance\", datname=~\"($db)\"})) by (datname))",
     "legendFormat": "{{datname}} Cache Hit Rate"
    }
   ]
  },
  {
   "title": "Top 100 Lock Tables",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "topk(100, max(pg_lock_count{instance=\"$instance\", datname=~\"($db)\"}) by (datname, mode))",
     "legendFormat": "{{datname}} {{mode}}"
    }
   ]
  },
  {
   "title": "Top 100 Temp File",
   "type": "timeseries",
   "description": "Total amount of data written to temporary files by queries in this database. All temporary files are counted, regardless of why the temporary file was created, and regardless of the log_temp_files setting.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 106 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "topk(100, max(irate(pg_db_temp_bytes{instance=\"$instance\", datname=~\"($db)\"}[5m])) by (datname))",
     "legendFormat": "{{datname}} Temp Bytes"
    }
   ]
  },
  {
   "title": "Free percent space /dev/shm",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
   "targets": [
    {
     "expr": "(node_filesystem_avail_bytes{instance=~\"$node_instance\", mountpoint=\"/dev/shm\"} / node_filesystem_size_bytes{instance=~\"$node_instance\", mountpoint=\"/dev/shm\"}) * 100 ",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  { "title": "Table stats for only one DB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 119 } },
  {
   "title": "Idx_scan",
   "type": "timeseries",
   "description": "Количество сканирований по индексу, запущенных по этой таблице",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_table_idx_scan{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "table_idx_scan {{datname}}: {{relname}}"
    }
   ]
  },
  {
   "title": "seq_scan",
   "type": "timeseries",
   "description": "Количество последовательных чтений, запущенных по этой таблице",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_table_seq_scan{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "table_seq_scan {{datname}}: {{relname}}"
    }
   ]
  },
  {
   "title": "idx_tup_fetch",
   "type": "timeseries",
   "description": "Количество сканирований по индексу, запущенных по этой таблице",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_table_idx_tup_fetch{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "table_idx_scan {{datname}}: {{relname}}"
    }
   ]
  },
  {
   "title": "seq_tup_read",
   "type": "timeseries",
   "description": "Количество последовательных чтений, запущенных по этой таблице",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 127 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_table_seq_tup_read{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "table_seq_scan {{datname}}: {{relname}}"
    }
   ]
  },
  {
   "title": "Read table blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_table_heap_blks_read{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "heap_blks_read {{datname}}.{{relname}}"
    },
    {
     "expr": "irate(pg_table_heap_blks_hit{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "heap_blks_hit {{datname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Read index blocks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_table_idx_blks_read{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "idx_blks_read {{datname}}.{{relname}}"
    },
    {
     "expr": "irate(pg_table_idx_blks_hit{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "idx_blks_hit {{datname}}.{{relname}}"
    }
   ]
  },
  {
   "title": "Percent of dead rows",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum((pg_table_n_dead_tup{instance=\"$instance\",datname=\"$db\"}) / ((pg_table_n_live_tup{instance=\"$instance\",datname=\"$db\"})/100)) by (instance, datname, relname) > 0",
     "legendFormat": "{{ datname }} {{ relname }}"
    }
   ]
  },
  {
   "title": "change stats",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 141 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "irate(pg_table_n_tup_del{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "delete {{datname}}: {{relname}}"
    },
    {
     "expr": "irate(pg_table_n_tup_upd{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "update {{datname}}: {{relname}}"
    },
    {
     "expr": "irate(pg_table_n_tup_ins{instance=\"$instance\",datname=\"$db\"}[5m])",
     "legendFormat": "insert {{datname}}: {{relname}}"
    }
   ]
  },
  {
   "title": "Table size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(pg_table_size_bytes{instance=\"$instance\", datname=\"$db\"}) by (relname)",
     "legendFormat": "{{datname}}"
    },
    {
     "expr": "sum(max(pg_table_size_bytes{instance=\"$instance\", datname=\"$db\"}) by (table_name))",
     "legendFormat": "All Tables"
    }
   ]
  },
  {
   "title": "Rows count in table",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 148 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(pg_table_tuples{instance=\"$instance\", datname=\"$db\"}) by (relname)",
     "legendFormat": "{{datname}}"
    }
   ]
  },
  { "title": "misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 155 } },
  {
   "title": "Buffers (bgwriter)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(irate(pg_bgwriter_buffers_backend{instance=\"$instance\"}[5m]))",
     "legendFormat": "buffers_backend"
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_buffers_alloc{instance=\"$instance\"}[5m]))",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_buffers_backend_fsync{instance=\"$instance\"}[5m]))",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_buffers_checkpoint{instance=\"$instance\"}[5m]))",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_buffers_clean{instance=\"$instance\"}[5m]))",
     "legendFormat": "buffers_clean"
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_bgw_buffers_alloc{namespace=\"$namespace\", instance=\"$instance\"}[5m]))",
     "legendFormat": "buffers_alloc"
    },
    {
     "expr": "max(irate(pg_stat_io_sum_fsyncs{namespace=\"$namespace\", instance=\"$instance\"}[5m]))",
     "legendFormat": "backend_fsync"
    },
    {
     "expr": "max(irate(pg_stat_checkpointer_checkpoint_buffers_written{namespace=\"$namespace\", instance=\"$instance\"}[5m]))",
     "legendFormat": "buffers_checkpoint"
    },
    {
     "expr": "max(irate(pg_stat_bgwriter_bgw_buffers_clean{namespace=\"$namespace\", instance=\"$instance\"}[5m]))",
     "legendFormat": "buffers_clean"
    }
   ]
  },
  {
   "title": "Conflicts/Deadlocks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 156 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(irate(pg_db_conflicts{instance=\"$instance\"}[5m])) by (datname)",
     "legendFormat": "{{datname}} conflicts"
    },
    {
     "expr": "max(irate(pg_db_deadlocks{instance=\"$instance\"}[5m])) by (datname)",
     "legendFormat": "{{datname}} deadlocks"
    }
   ]
  },
  {
   "title": "Checkpoint Stats",
   "type": "timeseries",
   "description": "- write_time - Total amount of time that has been spent in the portion of checkpoint processing where files are written to disk.\n- sync_time - Total amount of time that has been spent in the portion of checkpoint processing where files are synchronized to disk.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 162 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "max(irate(pg_bgwriter_checkpoint_write_time{instance=\"$instance\"}[5m]))",
     "legendFormat": "write_time"
    },
    {
     "expr": "max(irate(pg_bgwriter_checkpoint_sync_time{instance=\"$instance\"}[5m]))",
     "legendFormat": "sync_time"
    },
    {
     "expr": "max(irate(pg_checkpointer_write_time{namespace=\"$namespace\", instance=\"$instance\"}[5m]))",
     "legendFormat": "write_time"
    },
    {
     "expr": "max(irate(pg_checkpointer_sync_time{namespace=\"$namespace\", instance=\"$instance\"}[5m]))",
     "legendFormat": "sync_time"
    }
   ]
  },
  { "title": "Информация по Bloat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 171 } },
  {
   "title": "Раздутие таблиц (ratio)",
   "type": "timeseries",
   "description": "Процентное соотношение текущего размера таблицы с учетом раздутия к её оригинальному размеру; обновляется раз в 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_table_bloat_ratio{instance=~\"$instance\",datname=~\"$db\"}",
     "legendFormat": "{{datname}}::{{relname}}"
    }
   ]
  },
  {
   "title": "Раздутие таблиц (mb)",
   "type": "timeseries",
   "description": "Насколько таблицы раздулась из-за большого количества мертвых строк и их последующей очистки; обновляется раз в 5 минут",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 172 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_table_bloat_size{instance=~\"$instance\", datname=~\"$db\"} * pg_table_bloat_ratio{instance=~\"$instance\",datname=~\"$db\"}",
     "legendFormat": "{{datname}}::{{relname}}"
    }
   ]
  },
  {
   "title": "Раздутие индексов (ratio)",
   "type": "timeseries",
   "description": "Процентное соотношение текущего размера индекса с учетом раздутия к его оригинальному размеру; обновляется раз в 5 минут",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "pg_index_bloat_ratio{instance=~\"$instance\",datname=~\"$db\"}",
     "legendFormat": "{{datname}}::{{relname}}"
    }
   ]
  },
  {
   "title": "Раздутие индексов (mb)",
   "type": "timeseries",
   "description": "Насколько индексы раздулась из-за большого количества мертвых строк и их последующей очистки; обновляется раз в 5 минут",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 180 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "pg_index_bloat_size{instance=~\"$instance\",datname=~\"$db\"}*pg_index_bloat_ratio{instance=~\"$instance\",datname=~\"$db\"}",
     "legendFormat": "{{datname}}::{{relname}}"
    }
   ]
  }
 ]
}