apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-datasource
  namespace: {{ .Values.namespace }}
  labels:
    grafana_datasource: "1"
data:
  clickhouse-datasource.yaml: |
    apiVersion: 1
    datasources:
      {{- range .Values.clickhouseClusters }}
      - name: {{ .name }}
        type: vertamedia-clickhouse-datasource
        url: {{ .url }}
        access: proxy
        basicAuth: true
        basicAuthUser: {{ .username }}
        secureJsonData:
          basicAuthPassword: {{ .password }}
        jsonData:
          usePost: true
          defaultDatabase: default
      {{- end }}
