{{- if .Values.imageRenderer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-image-renderer
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana-image-renderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-image-renderer
  template:
    metadata:
      labels:
        app: grafana-image-renderer
    spec:
      containers:
        - name: grafana-image-renderer
          image: {{ .Values.imageRenderer.image }}
          ports:
            - containerPort: {{ .Values.imageRenderer.port }}
          env:
            - name: ENABLE_METRICS
              value: "false"
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-image-renderer
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana-image-renderer
spec:
  selector:
    app: grafana-image-renderer
  ports:
    - port: {{ .Values.imageRenderer.port }}
      targetPort: {{ .Values.imageRenderer.port }}
{{- end }}
