apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: {{ .Values.namespace }}
  labels:
    grafana_datasource: "1"
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: Loki
        type: loki
        access: proxy
        url: {{ .Values.loki.url }}
        jsonData:
          maxLines: 1000
