apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: clickhouse-operator
  namespace: {{ .Values.namespace }}
spec:
  namespaceSelector:
    matchNames:
      - {{ .Values.clickhouseOperator.namespace }}
  selector:
    matchLabels:
      app.kubernetes.io/name: altinity-clickhouse-operator
      app.kubernetes.io/instance: clickhouse-operator
  endpoints:
    - port: ch-metrics
    - port: op-metrics
