apiVersion: v1
kind: ConfigMap
metadata:
  name: clickhouse-datasource
  namespace: monitoring
  labels:
    grafana_datasource: "1"
data:
  clickhouse-datasource.yaml: |
    apiVersion: 1
    datasources:
      - name: chi-test
        type: vertamedia-clickhouse-datasource
        url: http://clickhouse-chi-test.clickhouse.svc.cluster.local:8123
        access: proxy
        basicAuth: true
        basicAuthUser: monitoring
        secureJsonData:
          basicAuthPassword: monitoring
        jsonData:
          usePost: true
          defaultDatabase: default
      - name: chi-test-2
        type: vertamedia-clickhouse-datasource
        url: http://clickhouse-chi-test-2.clickhouse-2.svc.cluster.local:8123
        access: proxy
        basicAuth: true
        basicAuthUser: monitoring
        secureJsonData:
          basicAuthPassword: monitoring
        jsonData:
          usePost: true
          defaultDatabase: default

