apiVersion: "clickhouse.altinity.com/v1"
kind: ClickHouseInstallation
metadata:
  name: chi-test
  namespace: clickhouse
spec:
  configuration:
    users:
      monitoring/password: "monitoring"
      monitoring/networks/ip:
        - "::/0"
      monitoring/profile: readonly
    clusters:
      - name: "test"
        layout:
          shardsCount: 1
          replicasCount: 2

