apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.clusterName }}-metrics
  namespace: {{ .Values.namespace }}
  labels:
    application: spilo
    cluster-name: {{ .Values.clusterName }}
spec:
  selector:
    application: spilo
    cluster-name: {{ .Values.clusterName }}
  clusterIP: None
  ports:
    - name: pg-exporter
      port: 9187
      targetPort: 9187
    - name: patroni
      port: 8008
      targetPort: 8008
    - name: walg-exporter
      port: 9351
      targetPort: 9351
    - name: pgsty-exporter
      port: 9630
      targetPort: 9630
