apiVersion: v1
kind: Service
metadata:
  name: chi-test-2-backup-metrics
  namespace: clickhouse-2
  labels:
    clickhouse.altinity.com/chi: chi-test-2
spec:
  selector:
    clickhouse.altinity.com/chi: chi-test-2
  clusterIP: None
  ports:
    - name: backup-api
      port: 7171
      targetPort: 7171
