apiVersion: v1
kind: Service
metadata:
  name: chi-test-backup-metrics
  namespace: clickhouse
  labels:
    clickhouse.altinity.com/chi: chi-test
spec:
  selector:
    clickhouse.altinity.com/chi: chi-test
  clusterIP: None
  ports:
    - name: backup-api
      port: 7171
      targetPort: 7171
